import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,webcrypto} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {ROOMS,AREA_TOTAL,AREA_SECOND_FLOOR,NODES,EDGES,TASKS,STEPS,SNAPSHOT,sourceFacts,filteredTasks,makeEvent,hashEvents,adjacentNodeIds} from '../../apps/web/src/components/life/spatial/spatial-data.mjs';
import {SCENE_SPEC} from '../../apps/web/src/components/life/spatial/scene-spec.mjs';
import {sha256Hex} from '../../apps/web/src/components/life/spatial/sha256.mjs';
const same=(a,b)=>assert.deepEqual(a,b);
test('Scope is exactly the four authorized planning inputs',()=>same(ROOMS.map(r=>r.id),['L112','L203','L202','L201']));
test('Total uses integer-cent precision: 671.26',()=>assert.equal(ROOMS.reduce((s,r)=>s+Math.round(r.area*100),0),Math.round(AREA_TOTAL*100)));
test('2F total is 612.57, with source drawing order preserved',()=>{const second=ROOMS.filter(r=>r.floor==='2F');same(second.map(r=>r.id),['L203','L202','L201']);assert.equal(second.reduce((s,r)=>s+Math.round(r.area*100),0),Math.round(AREA_SECOND_FLOOR*100));});
test('Areas match individual supplied source values',()=>same(ROOMS.map(r=>r.area),[58.69,135.8,185.99,290.78]));
test('Unknown rights remain null and all services remain closed',()=>ROOMS.forEach(r=>{assert.equal(r.lease,null);assert.equal(r.open,false);assert.equal(r.sceneBinding,null);}));
test('Source pages are 2 for 1F and 3 for 2F',()=>ROOMS.forEach(r=>assert.equal(r.page,r.floor==='1F'?2:3)));
test('Scene geometry never promotes into measured navigation',()=>{assert.equal(SCENE_SPEC.surveyed,false);assert.equal(SCENE_SPEC.navmesh,false);assert.equal(SCENE_SPEC.collisionMap,false);assert.equal(SCENE_SPEC.units,'schematic_scene_units');});
test('Geometry has exactly four room IDs and stays within 500-object budget',()=>{same([...new Set(SCENE_SPEC.objects.map(o=>o.room))],ROOMS.map(r=>r.id));assert(SCENE_SPEC.objects.length<500);});
test('Object names are unique and numeric coordinates finite',()=>{assert.equal(new Set(SCENE_SPEC.objects.map(o=>o.name)).size,SCENE_SPEC.objects.length);for(const o of SCENE_SPEC.objects){for(const v of [...(o.loc||[]),...(o.size||[]),...(o.polygon||[]).flat()])assert(Number.isFinite(v));}});
test('Logical edges reference defined nodes',()=>EDGES.flat().forEach(id=>assert(NODES.some(n=>n.id===id))));
test('Neighborhood selection is symmetric and includes itself',()=>{assert(adjacentNodeIds('human').has('human'));assert(adjacentNodeIds('human').has('cai'));assert(adjacentNodeIds('cai').has('human'));assert(!adjacentNodeIds('human').has('L112'));});
test('Tasks are synthetic review-only fixtures',()=>TASKS.forEach(t=>{assert.match(t.id,/^DEMO-/);assert.equal(t.purpose,'REVIEW_ONLY');assert(ROOMS.some(r=>r.id===t.room));}));
test('Task filter does not manufacture tasks',()=>{assert.equal(filteredTasks('ALL').length,4);same(filteredTasks('BLOCKED').map(t=>t.id),['DEMO-003']);assert.equal(filteredTasks('invalid').length,0);});
test('Five AHIN labels remain local unsigned demonstration events',()=>{same(STEPS.map(s=>s.action),['ASSERT','REASON','DELEGATE','FULFILL','CHALLENGE']);for(let i=0;i<5;i++){const e=makeEvent(i);assert(e.isDemo);assert(!e.signed);assert(!e.finalAuthority);assert(!e.executedExternalAction);}});
test('Malformed event indexes and unknown tasks fail closed',()=>{for(const i of [-1,5,1.1,NaN])assert.throws(()=>makeEvent(i));assert.throws(()=>makeEvent(0,'REAL-001'));});
for(const [label,txt] of [['empty',''],['abc','abc'],['unicode','Life++ 生生不息 / CoHERE'],['multi-block','x'.repeat(1000)]])test('SHA-256 fallback matches native crypto: '+label,()=>assert.equal(sha256Hex(new TextEncoder().encode(txt)),createHash('sha256').update(txt).digest('hex')));
test('Native WebCrypto and offline chains are identical',async()=>{const e=STEPS.map((_,i)=>makeEvent(i));same(await hashEvents(e,webcrypto),await hashEvents(e,null));});
test('A changed event changes all subsequent hashes',async()=>{const e=STEPS.map((_,i)=>makeEvent(i));const a=await hashEvents(e,null);const b=await hashEvents(e.map((v,i)=>i===1?{...v,actor:'demo:other'}:v),null);assert.equal(a[0].hash,b[0].hash);for(let i=1;i<5;i++)assert.notEqual(a[i].hash,b[i].hash);});
test('Snapshot is explicit HOLD, not fresh UI or whole-app CI',()=>{assert.equal(SNAPSHOT.release,'HOLD');assert.equal(SNAPSHOT.trustGate,'FAIL');assert.equal(SNAPSHOT.highFindings,4);assert.equal(SNAPSHOT.production,'NOT_DEPLOYED');assert(!SNAPSHOT.robotCommands);assert(!SNAPSHOT.billing);assert(!SNAPSHOT.telemetry);assert.equal(sourceFacts().leaseVerified,false);});
test('Authored engine has no external API, storage or event-beacon call',()=>{for(const name of readdirSync(new URL('../../apps/web/src/components/life/spatial/',import.meta.url)).filter(n=>n.endsWith('.mjs'))){const text=readFileSync(new URL('../../apps/web/src/components/life/spatial/'+name,import.meta.url),'utf8');assert(!/\b(?:fetch|WebSocket|XMLHttpRequest|sendBeacon)\s*\(/.test(text),name);assert(!/\b(?:localStorage|sessionStorage)\b/.test(text),name);}});
