import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { cleanupInquiries, inquiryStatus, maintainInquiries, parseInquiryConfig, parseSubmittedInquiry, submitInquiry, withdrawInquiry, type InquiryConfig, type InquiryRuntime } from '../../apps/web/src/lib/life/inquiry-service';

const config: InquiryConfig = { enabled:true, origin:'https://inquiry.example.test', retentionDays:2, policyVersion:'fixture-v1', acceptanceRef:'LOCAL_SYNTHETIC-acceptance', controller:'LOCAL_SYNTHETIC recipient', backupNoticeZh:'本地合成测试，无生产备份声明。', backupNoticeEn:'Local synthetic test; no production backup claim.', hmacKey:'LOCAL_SYNTHETIC-hmac-key-not-a-secret-0000', maintenanceToken:'LOCAL_SYNTHETIC-maintenance-token-0000' };
const inquiry = { name:'LOCAL_SYNTHETIC visitor',organization:'',channel:'email',contact:'test@example.invalid',type:'space',message:'LOCAL_SYNTHETIC consultation test. No real user or recipient.',consent:true };
const makeBody=(overrides:Record<string,unknown>={})=>({inquiry,idempotencyKey:crypto.randomUUID(),policyVersion:config.policyVersion,sendConsent:true,website:'',...overrides});
const request=(data:unknown,headers:Record<string,string>={},method='POST')=>new Request(`${config.origin}/life/inquiries`,{method,headers:{'content-type':'application/json','origin':config.origin,'sec-fetch-site':'same-origin','x-lifepp-inquiry':'1',...headers},body:JSON.stringify(data)});

test('consultation defaults closed and rejects incomplete configuration / untrusted schema',async()=>{
 assert.equal(await (await inquiryStatus(null)).text(),'{"mode":"draft"}');
 assert.equal((await submitInquiry(request(makeBody()),null,'192.0.2.1')).status,503);
 assert.equal(parseInquiryConfig({}),null);
 const environment={LIFEPP_INQUIRY_ENABLED:'true',LIFEPP_INQUIRY_SITE_ORIGIN:config.origin,LIFEPP_INQUIRY_RETENTION_DAYS:String(config.retentionDays),LIFEPP_INQUIRY_POLICY_VERSION:config.policyVersion,LIFEPP_INQUIRY_ACCEPTANCE_REF:config.acceptanceRef,LIFEPP_INQUIRY_CONTROLLER:config.controller,LIFEPP_INQUIRY_BACKUP_NOTICE_ZH:config.backupNoticeZh,LIFEPP_INQUIRY_BACKUP_NOTICE_EN:config.backupNoticeEn,LIFEPP_INQUIRY_HMAC_KEY:config.hmacKey,LIFEPP_INQUIRY_MAINTENANCE_TOKEN:config.maintenanceToken};
 assert.deepEqual(parseInquiryConfig(environment),config);
 assert.equal(parseInquiryConfig({...environment,LIFEPP_INQUIRY_ENABLED:undefined})?.enabled,false,'Configuration never enables collection without an explicit server flag');
 for(const overrides of [{LIFEPP_INQUIRY_SITE_ORIGIN:'http://inquiry.example.test'},{LIFEPP_INQUIRY_SITE_ORIGIN:`${config.origin}/path`},{LIFEPP_INQUIRY_RETENTION_DAYS:'0'},{LIFEPP_INQUIRY_RETENTION_DAYS:'31'},{LIFEPP_INQUIRY_CONTROLLER:''},{LIFEPP_INQUIRY_BACKUP_NOTICE_EN:undefined},{LIFEPP_INQUIRY_HMAC_KEY:'short'},{LIFEPP_INQUIRY_MAINTENANCE_TOKEN:config.hmacKey}])assert.equal(parseInquiryConfig({...environment,...overrides}),null);
 for(const value of [null,{},[],makeBody({sendConsent:false}),makeBody({sendConsent:undefined}),makeBody({website:'spam'}),makeBody({inquiry:{...inquiry,consent:false}}),makeBody({inquiry:{...inquiry,message:17}}),makeBody({inquiry:{...inquiry,extra:'smuggled'}}),makeBody({idempotencyKey:'bad'}),makeBody({extra:true})])assert.equal(parseSubmittedInquiry(value),null);
 assert.ok(parseSubmittedInquiry(makeBody()));
});

test('LOCAL_SYNTHETIC D1 persistence, admission, withdrawal and cleanup stay fail-closed',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'lifepp-consultation-'));
 let mf:Miniflare|undefined;
 const open=async()=>{mf=new Miniflare({...convertV4MiniflareOptions({modules:true,script:'export default { fetch() { return new Response("LOCAL_SYNTHETIC"); } };',compatibilityDate:'2026-06-17',d1Databases:{LIFEPP_INQUIRY_DB:'local-synthetic-inquiries'}}),resourcePersistencePath:directory,cf:false,telemetry:{enabled:false}});return await mf.getD1Database('LIFEPP_INQUIRY_DB');};
 const now=Date.now();
 try{
  let db=await open();
  await db.exec((await readFile('apps/web/migrations/life-inquiry/0001_inquiry.sql','utf8')).replace(/--[^\n]*/g,'').replace(/\s+/g,' '));
  let runtime:InquiryRuntime={db,config};
  assert.equal((await (await inquiryStatus(runtime,now)).json()).mode,'draft','Schema alone cannot activate collection');
  await db.batch([db.prepare("INSERT INTO lifepp_inquiry_control(key,value) VALUES ('acceptance_ref',?)").bind(config.acceptanceRef),db.prepare("INSERT INTO lifepp_inquiry_control(key,value) VALUES ('policy_version',?)").bind(config.policyVersion)]);
  assert.equal((await (await inquiryStatus(runtime,now)).json()).mode,'draft','Missing cleanup heartbeat cannot activate collection');
  assert.equal((await maintainInquiries(new Request(config.origin,{method:'POST'}),runtime,now)).status,401);
  assert.equal((await maintainInquiries(new Request(config.origin,{method:'POST',headers:{authorization:`Bearer ${config.maintenanceToken}`}}),runtime,now)).status,200);
  assert.equal((await (await inquiryStatus(runtime,now)).json()).mode,'receive');
  assert.equal((await (await inquiryStatus({...runtime,config:{...config,enabled:false}},now)).json()).mode,'draft');
  for(const headers of [{origin:'https://attacker.example'},{'sec-fetch-site':'cross-site'},{'x-lifepp-inquiry':'bad'}])assert.equal((await submitInquiry(request(makeBody(),headers),runtime,'192.0.2.1',now)).status,403);
  assert.equal((await submitInquiry(request(makeBody()),runtime,null,now)).status,503);
  assert.equal((await submitInquiry(request(makeBody(),{'content-type':'text/plain'}),runtime,'192.0.2.1',now)).status,400);
  assert.equal((await submitInquiry(request({x:'a'.repeat(9000)}),runtime,'192.0.2.1',now)).status,400);
  assert.equal((await submitInquiry(request(makeBody({policyVersion:'old'})),runtime,'192.0.2.1',now)).status,409);
  assert.equal((await submitInquiry(request(makeBody({sendConsent:false})),runtime,'192.0.2.1',now)).status,400);
  assert.equal((await submitInquiry(request(makeBody({sendConsent:undefined})),runtime,'192.0.2.1',now)).status,400);
  const payload=makeBody();
  const first=await submitInquiry(request(payload),runtime,'192.0.2.1',now);assert.equal(first.status,201);
  const receipt=await first.json();assert.equal(receipt.status,'stored');assert.equal(receipt.duplicate,false);
  const duplicate=await submitInquiry(request(payload),runtime,'192.0.2.1',now);assert.equal(duplicate.status,200);assert.equal((await duplicate.json()).receiptId,receipt.receiptId);
  assert.equal((await submitInquiry(request({...payload,inquiry:{...inquiry,message:'Different LOCAL_SYNTHETIC payload.'}}),runtime,'192.0.2.1',now)).status,409);
  const updatedPolicy='fixture-v2';
  await db.prepare("UPDATE lifepp_inquiry_control SET value=? WHERE key='policy_version'").bind(updatedPolicy).run();
  assert.equal((await submitInquiry(request({...payload,policyVersion:updatedPolicy}),{db,config:{...config,policyVersion:updatedPolicy}},'192.0.2.1',now)).status,409,'A different consent policy cannot silently reuse an old-policy receipt');
  await db.prepare("UPDATE lifepp_inquiry_control SET value=? WHERE key='policy_version'").bind(config.policyVersion).run();
  assert.equal((await submitInquiry(request(makeBody()),runtime,'192.0.2.1',now)).status,201);
  assert.equal((await submitInquiry(request(makeBody()),runtime,'192.0.2.1',now)).status,201);
  for(let i=0;i<6;i++)assert.equal((await submitInquiry(request(makeBody()),runtime,'192.0.2.1',now)).status,429);
  assert.equal((await db.prepare('SELECT count FROM lifepp_inquiry_limits WHERE bucket=?').bind(`global:${Math.floor(now/3_600_000)}`).first())?.count,3,'Rejected client requests and duplicate retries cannot consume the global budget');
  const row=await db.prepare('SELECT * FROM lifepp_inquiries WHERE id=?').bind(receipt.receiptId).first();assert.ok(row);assert.match(String(row.body),/LOCAL_SYNTHETIC/);assert.equal('ip' in row,false);assert.equal(row.send_consent,1);assert.equal(String(row.withdrawal_hash).includes(receipt.withdrawalToken),false);
  await mf!.dispose();db=await open();runtime={db,config};
  const reopened=await db.prepare('SELECT body FROM lifepp_inquiries WHERE id=?').bind(receipt.receiptId).first();assert.equal(reopened?.body,row.body,'Actual local D1 persists after runtime restart');
  assert.equal((await withdrawInquiry(request({receiptId:receipt.receiptId,withdrawalToken:'0'.repeat(64)},{},'DELETE'),runtime)).status,403);
  assert.equal((await withdrawInquiry(request({receiptId:receipt.receiptId,withdrawalToken:receipt.withdrawalToken},{},'DELETE'),runtime)).status,200);
  assert.equal(await db.prepare('SELECT id FROM lifepp_inquiries WHERE id=?').bind(receipt.receiptId).first(),null);
  const withdrawnRetry=await submitInquiry(request(payload),runtime,'192.0.2.1',now);assert.equal(withdrawnRetry.status,409);assert.equal((await withdrawnRetry.json()).error,'withdrawn','Old retries cannot recreate withdrawn personal data');
  const withdrawalMarker=await db.prepare('SELECT * FROM lifepp_inquiry_withdrawals').first();assert.ok(withdrawalMarker);assert.deepEqual(Object.keys(withdrawalMarker).sort(),['expires_at','idempotency_key']);assert.equal(withdrawalMarker.expires_at,row.expires_at);
  const second=await submitInquiry(request(makeBody()),runtime,'192.0.2.2',now);assert.equal(second.status,201);
  const concurrent=await Promise.all(Array.from({length:8},()=>submitInquiry(request(makeBody()),runtime,'192.0.2.9',now)));
  assert.equal(concurrent.filter(response=>response.status===201).length,3,'Atomic distributed budget admits at most three concurrent new submissions');
  assert.equal(concurrent.filter(response=>response.status===429).length,5);
  const repeatedPayload=makeBody();
  const repeated=await Promise.all(Array.from({length:8},()=>submitInquiry(request(repeatedPayload),runtime,'192.0.2.10',now)));
  assert.equal(repeated.filter(response=>response.status===201).length,1,'Concurrent identical requests create one stored record');
  assert.equal(repeated.filter(response=>response.status===200).length,7);
  const repeatedReceipts=await Promise.all(repeated.map(response=>response.json()));
  assert.equal(new Set(repeatedReceipts.map(receipt=>receipt.receiptId)).size,1);
  const admitted=Number((await db.prepare('SELECT count FROM lifepp_inquiry_limits WHERE bucket=?').bind(`global:${Math.floor(now/3_600_000)}`).first())?.count);
  const remaining=100-admitted;
  const globalAdmission=await Promise.all(Array.from({length:remaining+5},(_,index)=>submitInquiry(request(makeBody()),runtime,`192.0.3.${index+1}`,now)));
  assert.equal(globalAdmission.filter(response=>response.status===201).length,remaining,'Concurrent distinct clients cannot exceed the global hourly budget');
  assert.equal(globalAdmission.filter(response=>response.status===429).length,5);
  assert.equal((await submitInquiry(request(repeatedPayload),runtime,'192.0.2.10',now)).status,200,'Existing receipt retries remain available after the global budget is exhausted');
  assert.equal((await (await inquiryStatus(runtime,now+3_600_001)).json()).mode,'draft','Stale cleanup stops new collection');
  assert.equal((await submitInquiry(request(makeBody()),runtime,'192.0.2.3',now+3_600_001)).status,503);
  await cleanupInquiries(runtime,now+3*86_400_000);
  assert.equal((await db.prepare('SELECT COUNT(*) AS count FROM lifepp_inquiries').first<{count:number}>())?.count,0);
  assert.equal((await db.prepare('SELECT COUNT(*) AS count FROM lifepp_inquiry_limits').first<{count:number}>())?.count,0);
  assert.equal((await db.prepare('SELECT COUNT(*) AS count FROM lifepp_inquiry_withdrawals').first<{count:number}>())?.count,0,'Minimal withdrawal markers expire with the original retention period');
  await db.exec('DROP TABLE lifepp_inquiries');
  assert.equal((await (await inquiryStatus(runtime,now+3*86_400_000)).json()).mode,'draft','Missing storage cannot advertise receiving');
  assert.equal((await submitInquiry(request(makeBody()),runtime,'192.0.2.3',now+3*86_400_000)).status,503,'Failed persistence never returns success');
 }finally{await mf?.dispose();await rm(directory,{recursive:true,force:true});}
});
