import {ROOMS,NODES,EDGES,TASKS,STEPS,SNAPSHOT,SOURCE_HEAD,sourceFacts,filteredTasks,makeEvent,hashEvents} from './spatial-data.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={space:'M3 8 12 3l9 5v9l-9 5-9-5V8Zm0 0 9 5 9-5M12 13v9',network:'M7 6h10M6 7l5 10m7-10-5 10M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm12 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm-6 14a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z',ops:'M5 4h14v17H5V4Zm4-2h6v4H9V2ZM9 10h6m-6 4h6m-6 4h4',evidence:'m12 2 8 3v7c0 5-8 10-8 10S4 17 4 12V5l8-3Zm-4 10 3 3 5-6',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M5 12h14m-7-7v14',minus:'M5 12h14',reset:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',focus:'M3 9V3h6m6 0h6v6M3 15v6h6m6 0h6v-6',plane:'M3 4h18v16H3V4Zm7 0v16M10 11h11',robot:'M5 7h14v12H5V7Zm7-4v4M8 12h1m6 0h1m-8 4h8M3 10v6m18-6v6',close:'m6 6 12 12M6 18 18 6',export:'M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5',play:'m8 4 12 8-12 8V4Z'};
const icon=(type)=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[type]||paths.space}"/></svg>`;
let serial=0;
/** The review harness and the Next client wrapper mount this identical engine. */
export function mountSpatialOperations(root,{locale='zh',loadScene=true}={}) {
 const zh=locale==='zh',t=(cn,en)=>zh?cn:en;const uid=`spatial-${++serial}`;
 let activeTab='space',selectedRoom='L203',selectedNode='cai',floor='ALL',scene=null,disposed=false,timer=null,step=-1,task=TASKS[0],opFilter='ALL',hashGeneration=0;const pendingUrls=new Map();
 const listeners=[]; const bind=(el,type,fn,opts)=>{el.addEventListener(type,fn,opts);listeners.push(()=>el.removeEventListener(type,fn,opts));};
 const q=s=>root.querySelector(s),qa=s=>[...root.querySelectorAll(s)];
 root.classList.add('ls-app');root.lang=zh?'zh-CN':'en';root.dataset.mode='review';root.dataset.externalActions='0';
 const tabNames=[['space',t('空间','Space')],['network',t('协作网络','Network')],['ops',t('运营回放','Operations')],['evidence',t('证据与门槛','Evidence')]];
 root.innerHTML=`
 <div class="ls-heading"><div><p class="ls-eyebrow">LIFE++ × CoHERE <span> / </span> SPATIAL OPERATIONS</p><h2>${t('空间可感知，协作可问责。','Visible spaces. Accountable collaboration.')}</h2><p class="ls-subtitle">${t('671.26㎡四铺导入期 · 会展湾 · 在同一处看见空间、任务与边界。','A planned 671.26 m², four-unit introduction at Expo Bay. Space, tasks and boundaries in one place.')}</p></div><span class="ls-badge ls-purple">${t('交互示意 · 非实时','INTERACTIVE DEMO · NOT LIVE')}<i></i></span></div>
 <div class="ls-workbench">
  <aside class="ls-rail" aria-label="${t('工作台视图','Workbench views')}"><div class="ls-rail-mark" aria-hidden="true">++</div><div role="tablist" aria-label="${t('工作台功能','Workbench panels')}">${tabNames.map(([id,label])=>`<button type="button" role="tab" id="${uid}-tab-${id}" aria-controls="${uid}-panel-${id==='network'?'space':id}" aria-selected="${id==='space'}" tabindex="${id==='space'?0:-1}" data-tab="${id}" title="${label}">${icon(id)}<span>${label}</span></button>`).join('')}</div><div class="ls-rail-bottom"><span>CAI</span><small>REVIEW</small></div></aside>
  <div class="ls-body">
   <div class="ls-toolbar"><div><span class="ls-location-dot"></span><strong>CoHERE / ${t('四铺导入期','Four-unit plan')}</strong><span class="ls-toolbar-tag">${t('功能规划','PLANNED USES')}</span></div><div class="ls-toolbar-end"><span class="ls-muted">${t('非实时数据','NOT LIVE')}</span><span class="ls-badge ls-amber">HOLD</span></div></div>
   <div class="ls-kpis"><div><span>${t('规划空间','Planned units')}</span><strong>04<small>${t('个','units')}</small></strong></div><div><span>${t('导入期面积','Planned area')}</span><strong>671.26<small>m²</small></strong></div><div><span>${t('二层主体','Second floor')}</span><strong>612.57<small>m²</small></strong></div><div class="ls-kpi-state"><span>${t('真实接入','Live integration')}</span><strong>—<small>${t('尚未验收','Not accepted')}</small></strong></div></div>
   <section class="ls-panel" role="tabpanel" id="${uid}-panel-space" aria-labelledby="${uid}-tab-space">
    <div class="ls-panelbar"><div class="ls-segment" aria-label="${t('楼层筛选','Floor filter')}">${['ALL','1F','2F'].map(f=>`<button type="button" data-floor="${f}" aria-pressed="${f==='ALL'}">${f==='ALL'?t('全部楼层','All floors'):f}</button>`).join('')}</div><span class="ls-scene-caption">${t('按图定位示意 · 非测绘 / 导航地图','Drawing-derived schematic · Not a survey or navigation map')}</span><button type="button" class="ls-text-button" data-action="plan">${icon('plane')}${t('原图说明','Plan reference')}</button></div>
    <div class="ls-stage-grid"><div class="ls-stage-wrap"><div class="ls-stage" data-scene-state="loading" aria-label="${t('四铺三维编排示意；可通过下方铺位按钮操作','Four-unit 3D schematic; use the unit buttons below for keyboard access')}"></div><div class="ls-canvas-loading">${t('准备本地三维视图…','Preparing the local 3D view…')}</div><div class="ls-stage-tag"><span class="ls-small-dot"></span><strong class="ls-stage-title">${t('四铺空间编排','Four-unit spatial composition')}</strong><small class="ls-stage-sub">${t('示意层高 · 家具与设备为概念占位','Schematic elevations · Concept furniture & devices')}</small></div><div class="ls-stage-controls">${[['plus','zoom-in',t('放大','Zoom in')],['minus','zoom-out',t('缩小','Zoom out')],['focus','focus',t('聚焦选中对象','Focus selection')],['plane','top',t('切换俯视','Toggle top view')],['reset','reset',t('重置视角','Reset view')]].map(([i,a,l])=>`<button type="button" data-action="${a}" aria-label="${l}" title="${l}">${icon(i)}</button>`).join('')}</div><div class="ls-stage-bottom"><span>${t('拖动旋转 · 滚轮缩放 · Shift 拖动平移','Drag to orbit · Scroll to zoom · Shift-drag to pan')}</span><span class="ls-geometry">3D / ${t('示意坐标','SCENE UNITS')}</span></div></div><aside class="ls-inspector" aria-live="polite"></aside></div>
    <div class="ls-unit-list" aria-label="${t('选择铺位（键盘可操作）','Select a unit (keyboard accessible)')}"></div>
    <div class="ls-context"><div>${icon('evidence')}<strong>${t('可看见，不等于已获准。','Visibility is not authorization.')}</strong><span>${t('所有空间均为规划；当前没有真实调度、收费或场景 33 / 29 的资产接入。','All uses are planned. No real dispatch, billing or Scene 33 / 29 asset integration.')}</span></div><button type="button" data-action="evidence" class="ls-text-button">${t('查看证据与门槛','Review the gates')} ${icon('arrow')}</button></div>
   </section>
   <section class="ls-panel ls-ops-panel" role="tabpanel" id="${uid}-panel-ops" aria-labelledby="${uid}-tab-ops" hidden>
    <div class="ls-ops-heading"><div><p class="ls-eyebrow">LOCAL REPLAY / NO EXTERNAL ACTIONS</p><h3>${t('把一次协作，拆成可检查的步骤。','Inspect a collaboration, step by step.')}</h3><p>${t('以下 4 条均为合成任务夹具，不是订单、在线机器人或真实服务工单。','All four entries are synthetic fixtures, not orders, online robots or live service tickets.')}</p></div><span class="ls-badge ls-purple">DEMO DATA</span></div>
    <div class="ls-ops-grid"><div class="ls-task-panel"><div class="ls-task-filter"><strong>${t('任务样例','Sample tasks')}</strong><label>${t('状态','Status')} <select aria-label="${t('按任务状态筛选','Filter tasks by status')}" class="ls-task-select"><option value="ALL">${t('全部','All')}</option><option value="DRAFT">${t('草稿','Draft')}</option><option value="REVIEW">${t('待审阅','Review')}</option><option value="BLOCKED">${t('受阻','Blocked')}</option></select></label></div><div class="ls-tasks"></div><div class="ls-locked"><span>${icon('robot')}</span><strong>${t('真实调度保持关闭','Real dispatch remains off')}</strong><p>${t('尚未配置机器人网关、调度权限或外部接收端。回放不会发出动作指令。','No robot gateway, dispatch authority or external recipient is configured. Replay sends no motion command.')}</p><button type="button" disabled>${t('生产调度未开放','Production dispatch unavailable')}</button></div></div>
    <div class="ls-replay"><div class="ls-replay-head"><div><p class="ls-eyebrow">AHIN / DEMONSTRATION</p><h3>${t('责任事件回放','Responsibility event replay')}</h3></div><span class="ls-counter">0 / 5</span></div><ol class="ls-timeline">${STEPS.map((s,i)=>`<li data-step="${i}"><span class="ls-step-number">0${i+1}</span><div><strong>${s.action}</strong><b>${zh?s.zh:s.en}</b><p>${zh?s.noteZh:s.noteEn}</p></div><span class="ls-step-state">${t('未回放','Pending')}</span></li>`).join('')}</ol><div class="ls-replay-actions"><button type="button" class="ls-primary" data-action="play">${icon('play')}<span>${t('播放演示','Play demo')}</span></button><button type="button" class="ls-secondary" data-action="step">${t('下一步','Next step')}</button><button type="button" class="ls-text-button" data-action="clear">${t('清空回放','Clear replay')}</button></div><div class="ls-hash-note"><code class="ls-event-hash">${t('尚无演示事件','No demo event yet')}</code><p>${t('本地 SHA-256 链仅支持演示记录完整性；无签名，不证明权限、事实或实际履行。','The local SHA-256 chain supports demo-record integrity only. It is unsigned and proves neither permission, facts nor fulfillment.')}</p><button type="button" class="ls-text-button" data-action="export">${icon('export')}${t('导出演示记录','Export demo record')}</button></div></div></div>
   </section>
   <section class="ls-panel ls-evidence-panel" role="tabpanel" id="${uid}-panel-evidence" aria-labelledby="${uid}-tab-evidence" hidden></section>
   <div class="ls-footer"><span>Life++ / ${t('可感知 · 可审阅 · 不越权','Perceptible · Reviewable · Bounded')}</span><span>R3.2.1 · SCHEMATIC DEMO · ${t('历史状态快照','Historical snapshot')} 2026-10-05</span></div>
  </div>
 </div><div class="ls-toast" role="status" aria-live="polite"></div>
 <dialog class="ls-plan-dialog" aria-labelledby="${uid}-plan-title"><div class="ls-dialog-top"><h3 id="${uid}-plan-title">${t('原图与公开范围','Source plan and publication scope')}</h3><button type="button" data-action="close-plan" aria-label="${t('关闭说明','Close reference')}">${icon('close')}</button></div><p>${t('四铺位置参考原平面第2、3页。请使用本页上方保留的四铺原图组件；本交互模块不另行复制或发布附件中的平面图、完整PDF或GLB。','Locations refer to the original floorplan, pages 2 and 3. Use the existing four-unit plan above. This module does not copy or publish the attachment drawings, full PDFs or GLB.')}</p><p>${t('以下几何是人工绘制的功能示意，层高、家具与设备不是现场测量结果，也不构成租赁界线或导航许可。展示权不自动包含下载、训练、再分发与机器人使用权。','The geometry is a manually authored functional schematic. Heights, furniture and devices are not measured conditions, lease boundaries or navigation permission. Display rights do not automatically grant download, training, redistribution or robot-use rights.')}</p></dialog>`;
 const statusLabel=s=>({DRAFT:t('草稿','Draft'),REVIEW:t('待审阅','Review'),BLOCKED:t('受阻','Blocked')}[s]||s);
 function toast(message){q('.ls-toast').textContent=message;}
 function units(){
  const list=q('.ls-unit-list'),active=globalThis.document.activeElement;
  const focused=active&&list.contains(active)?active.closest('button[data-room],button[data-node]'):null;
  const focusKey=focused?.dataset.room?'room':'node',focusId=focused?.dataset[focusKey];
  if(activeTab==='network')q('.ls-unit-list').innerHTML=NODES.map(n=>`<button type="button" class="ls-unit ls-node-unit" data-node="${n.id}" aria-pressed="${selectedNode===n.id}"><span class="ls-unit-top"><b>${n.caption}</b></span><strong>${esc(zh?n.zh:n.en)}</strong><small>${t('逻辑节点 · 演示','Logical node · Demo')}</small></button>`).join('');
  else q('.ls-unit-list').innerHTML=ROOMS.filter(r=>floor==='ALL'||r.floor===floor).map(r=>`<button type="button" class="ls-unit" data-room="${r.id}" aria-pressed="${selectedRoom===r.id}"><span class="ls-unit-top"><b>${r.id}</b><small>${r.floor}</small></span><strong>${esc(zh?r.zh:r.en)}</strong><span><b>${r.area.toFixed(2)}</b> m² <small>${t('规划','Planned')}</small></span></button>`).join('');
  if(focusId){const replacement=[...list.querySelectorAll('button')].find(button=>button.dataset[focusKey]===focusId);replacement?.focus({preventScroll:true});}
 }
 function inspect(){
  if(activeTab==='network'){const n=NODES.find(x=>x.id===selectedNode)||NODES[1];const connected=EDGES.filter(e=>e.includes(n.id)).map(e=>e.find(v=>v!==n.id));q('.ls-inspector').innerHTML=`<p class="ls-eyebrow">LOGICAL RELATIONSHIPS</p><div class="ls-inspector-symbol">${icon('network')}</div><h3>${esc(zh?n.zh:n.en)}</h3><span class="ls-badge ls-purple">${t('逻辑关系演示','LOGICAL DEMO')}</span><dl><div><dt>${t('节点标识','Node ID')}</dt><dd>${n.id}</dd></div><div><dt>${t('展示连接','Shown connections')}</dt><dd>${connected.length}</dd></div><div><dt>${t('运行连接','Runtime connection')}</dt><dd>${t('未配置','Not configured')}</dd></div><div><dt>${t('最终授权','Final authority')}</dt><dd>${t('无 · 不可推导','None · Not inferred')}</dd></div></dl><h4>${t('关联节点','Connected nodes')}</h4><p class="ls-related">${connected.map(x=>esc(x)).join(' / ')}</p><div class="ls-inspector-note">${t('连线表示设计中的协作关系，不是可通行路线、网络实测拓扑或已生效委托。','Links represent designed relationships, not walkable routes, measured network topology or an active delegation.')}</div>`;return;}
  const r=ROOMS.find(r=>r.id===selectedRoom);q('.ls-inspector').innerHTML=`<p class="ls-eyebrow">SELECTED SPACE <span>/ ${r.floor}</span></p><div class="ls-room-id">${r.id}<span>${icon(r.id==='L112'?'robot':'space')}</span></div><h3>${esc(zh?r.zh:r.en)}</h3><p class="ls-inspector-description">${esc(zh?r.roleZh:r.roleEn)}</p><div class="ls-area"><strong>${r.area.toFixed(2)}</strong><span>m² / ${t('资料面积','Plan area')}</span></div><span class="ls-badge ls-purple">${t('拟议模块 · 待确认','PROPOSED · UNCONFIRMED')}</span><dl><div><dt>${t('来源','Source')}</dt><dd>${t('原平面','Floorplan')} · P${r.page}</dd></div><div><dt>${t('使用权 / 租约','Use rights / lease')}</dt><dd>${t('待核验','Unverified')}</dd></div><div><dt>${t('开放状态','Open status')}</dt><dd>${t('尚未开放','Not open')}</dd></div><div><dt>${t('3DGS 绑定','3DGS binding')}</dt><dd>${t('无已验证绑定','No verified binding')}</dd></div></dl><div class="ls-inspector-note">${t('面积来自用户提供资料；示意模型不定义租赁界线，不支持自动导航。','Areas come from supplied materials. The schematic defines neither lease boundaries nor autonomous navigation.')}</div><button type="button" class="ls-secondary ls-full" data-action="unit-task">${t('查看关联演示任务','View associated demo task')} ${icon('arrow')}</button>`;
 }
 function setSelection(id){if(activeTab==='network'){if(!NODES.some(n=>n.id===id))return;selectedNode=id;}else{const r=ROOMS.find(r=>r.id===id);if(!r)return;selectedRoom=id;if(floor!=='ALL'&&r.floor!==floor){floor=r.floor;qa('[data-floor]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.floor===floor));scene?.setFloor(floor);}}scene?.select(id);inspect();units();root.dataset.selected=id;}
 function pause(){if(timer!==null){globalThis.clearInterval(timer);timer=null;}q('[data-action="play"] span').textContent=t('播放演示','Play demo');}
 function tabs(id){activeTab=id;pause();qa('[data-tab]').forEach(b=>{const yes=b.dataset.tab===id;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;});
  q(`#${uid}-panel-space`).hidden=!['space','network'].includes(id);q(`#${uid}-panel-ops`).hidden=id!=='ops';q(`#${uid}-panel-evidence`).hidden=id!=='evidence';q(`#${uid}-panel-space`).setAttribute('aria-labelledby',`${uid}-tab-${id==='network'?'network':'space'}`);
  if(id==='space'||id==='network'){const net=id==='network';q('.ls-panelbar .ls-segment').hidden=net;q('[data-action="plan"]').hidden=net;q('.ls-scene-caption').textContent=net?t('逻辑协作关系 · 非运行拓扑 / 通行路径','Logical relationships · Not a runtime topology or route map'):t('按图定位示意 · 非测绘 / 导航地图','Drawing-derived schematic · Not a survey or navigation map');q('.ls-stage-title').textContent=net?t('人 × CAI × 空间 × 证据','Human × CAI × Space × Evidence'):t('四铺空间编排','Four-unit spatial composition');q('.ls-stage-sub').textContent=net?t('所有连线仅为设计关系；未连接生产系统','Design relationships only; no production connection'):t('示意层高 · 家具与设备为概念占位','Schematic elevations · Concept furniture & devices');if(scene?.info().renderer==='ThreeGeometryCanvas2D')q('.ls-stage-sub').textContent+=t(' · 软件示意 / WebGL 未验收，保持关闭',' · Software / WebGL not accepted; disabled');scene?.setMode(net?'network':'space');setSelection(net?selectedNode:selectedRoom);}
  scene?.setActive(['space','network'].includes(id)&&!globalThis.document.hidden);root.dataset.activeTab=id;
 }
 function tasks(){q('.ls-tasks').innerHTML=filteredTasks(opFilter).map(x=>`<button type="button" class="ls-task" data-task="${x.id}" aria-pressed="${x.id===task.id}"><span class="ls-task-meta"><code>${x.id}</code><span class="ls-state ls-state-${x.state.toLowerCase()}">${statusLabel(x.state)}</span></span><strong>${esc(zh?x.zh:x.en)}</strong><small>${x.room} <span>·</span> ${t('合成样例 · 无外部调用','Synthetic fixture · No external call')}</small></button>`).join('');}
 async function renderReplay(){const gen=++hashGeneration;q('.ls-counter').textContent=`${step+1} / 5`;qa('[data-step]').forEach(el=>{const i=Number(el.dataset.step);el.classList.toggle('is-played',i<=step);el.classList.toggle('is-current',i===step);el.querySelector('.ls-step-state').textContent=i<=step?t('已回放','Replayed'):t('未回放','Pending');});q('[data-action="step"]').disabled=step>=4;root.dataset.replayStep=String(step);
  if(step<0){q('.ls-event-hash').textContent=t('尚无演示事件','No demo event yet');return;}
  try{const events=await hashEvents(Array.from({length:step+1},(_,i)=>makeEvent(i,task.id)));if(disposed||gen!==hashGeneration)return;q('.ls-event-hash').textContent=`SHA-256 ${events.at(-1).hash.slice(0,24)}…`;q('.ls-event-hash').title=events.at(-1).hash;}catch{if(!disposed)q('.ls-event-hash').textContent=t('本环境无法计算 SHA-256；未生成完整性声明。','SHA-256 unavailable here; no integrity claim generated.');}
 }
 const nextStep=()=>{if(step<4){step++;void renderReplay();}if(step===4)pause();};
 async function exportRecord(){let events;try{events=await hashEvents(Array.from({length:step+1},(_,i)=>makeEvent(i,task.id)));}catch{if(disposed)return;toast(t('导出停止：无法计算哈希。请在 localhost 或 HTTPS 打开。','Export stopped: hashing unavailable. Use localhost or HTTPS.'));return;}if(disposed)return;
  const record={schema:'lifepp.spatial.local-replay.v1',createdAt:new Date().toISOString(),isDemo:true,signed:false,finalAuthority:false,executedExternalActions:0,claim:'Unsigned local demonstration. Not a delivery receipt, permission, verification or production audit.',facts:sourceFacts(),snapshot:SNAPSHOT,events};const blob=new globalThis.Blob([JSON.stringify(record,null,2)],{type:'application/json'}),url=globalThis.URL.createObjectURL(blob),a=globalThis.document.createElement('a');a.href=url;a.download='LifePP_DEMO_replay_NOT_PRODUCTION.json';a.click();const cleanup=globalThis.setTimeout(()=>{globalThis.URL.revokeObjectURL(url);pendingUrls.delete(url);},1000);pendingUrls.set(url,cleanup);toast(t('已导出本地演示 JSON；未发送至任何外部接收端。','Local demo JSON exported. Nothing sent to an external recipient.'));}
 function evidence(){const rows=[
  [t('历史候选快照','Historical candidate'),SOURCE_HEAD.slice(0,12),'SNAPSHOT'],[t('Life++ CI','Life++ CI'),'SUCCESS','green'],[t('完整 Trust Gate','Complete Trust Gate'),'FAIL · 4 HIGH','amber'],[t('场景 33 / 29','Scenes 33 / 29'),t('未真实加载','Real assets unverified'),'amber'],[t('场景 31','Scene 31'),t('历史兼容 · 独立资产','Legacy · Distinct asset'),'plain'],[t('咨询收件','Enquiry receipt'),t('草稿，尚未发送','Draft, not sent'),'plain'],[t('生产发布','Production release'),t('未合并 / 未部署','Not merged / Not deployed'),'amber']];
  q('.ls-evidence-panel').innerHTML=`<div class="ls-ops-heading"><div><p class="ls-eyebrow">SOURCE / SCOPE / STATUS</p><h3>${t('把未知保留下来，把发布边界写清楚。','Keep unknowns explicit. Keep release boundaries clear.')}</h3><p>${t('下列发布状态来自 2026-10-05 用户回执及 PR 快照，不是实时监控，也不是本 UI 的 CI 结果。','Release states below come from the 2026-10-05 user receipt and PR snapshot, not live monitoring or CI results for this UI.')}</p></div><span class="ls-badge ls-amber">RELEASE HOLD</span></div><div class="ls-evidence-grid"><article class="ls-evidence-card"><h4>${t('版本绑定的状态快照','Version-bound source snapshot')}</h4><dl>${rows.map(([a,b,c])=>`<div><dt>${a}</dt><dd class="ls-${c}">${b}</dd></div>`).join('')}</dl><code class="ls-long-code">${SOURCE_HEAD}</code><p class="ls-muted">${t('新增 UI 必须另行提交、审查并重跑最终 head 的完整 CI。这里不继承旧候选的绿色检查。','The new UI requires its own commit, review and complete final-head CI. Prior green checks are not inherited.')}</p></article><article class="ls-evidence-card"><h4>${t('进入真实运行前','Before real operation')}</h4><ol class="ls-gates">${[
  [t('依赖与发布路径','Dependencies & release paths'),t('解决 4 high；管理员整改两条独立 main 自动发布路径。','Resolve four high findings; an administrator must remediate both independent main auto-deploy paths.')],
  [t('最终版本审阅','Final-candidate review'),t('独立审阅、实际 main CI、制品与既有环境批准。','Independent review, actual main CI, artifact review and existing environment approval.')],
  [t('可验证回滚','Verified rollback'),t('完整 Worker version / deployment ID、健康与兼容性证明。','Complete Worker version / deployment IDs, health and compatibility evidence.')],
  [t('空间、设备与接收方','Spaces, devices & recipient'),t('分别核验 HTTPS、资产许可、安全范围与真实收件；不得由可视化自动推导。','Separately verify HTTPS, asset rights, safety scope and real receipt. Visualization grants none of these.')]
  ].map(([a,b],i)=>`<li><span>0${i+1}</span><div><strong>${a}</strong><p>${b}</p></div></li>`).join('')}</ol></article></div><div class="ls-evidence-boundary">${icon('evidence')}<div><strong>${t('本评审 UI：本地示意 + 合成回放','This review UI: local schematic + synthetic replay')}</strong><p>${t('无真实调度 · 无收费 · 无钱包操作 · 无训练销售 · 无认证签发。物理急停和安全控制不由浏览器界面代替。','No real dispatch, billing, wallet operation, training sales or certification. A browser interface does not replace physical emergency stops or safety controls.')}</p></div></div>`;
 }

 bind(root,'click',e=>{const b=e.target.closest('button');if(!b||!root.contains(b))return;if(b.dataset.tab){tabs(b.dataset.tab);return;}if(b.dataset.floor){floor=b.dataset.floor;qa('[data-floor]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.floor===floor)));scene?.setFloor(floor);const r=ROOMS.find(r=>r.id===selectedRoom);if(floor!=='ALL'&&r.floor!==floor)selectedRoom=ROOMS.find(r=>r.floor===floor).id;setSelection(selectedRoom);return;}if(b.dataset.room||b.dataset.node){setSelection(b.dataset.room||b.dataset.node);return;}if(b.dataset.task){pause();task=TASKS.find(x=>x.id===b.dataset.task);step=-1;tasks();void renderReplay();return;}
  switch(b.dataset.action){case'zoom-in':scene?.zoom(.82);break;case'zoom-out':scene?.zoom(1.22);break;case'reset':scene?.reset();break;case'focus':scene?.focus();break;case'top':scene?.top();break;case'evidence':tabs('evidence');break;case'plan':q('.ls-plan-dialog').showModal();break;case'close-plan':q('.ls-plan-dialog').close();break;case'unit-task':task=TASKS.find(x=>x.room===selectedRoom)||TASKS[0];opFilter='ALL';q('.ls-task-select').value='ALL';step=-1;tasks();void renderReplay();tabs('ops');break;case'clear':pause();step=-1;void renderReplay();break;case'step':pause();nextStep();break;case'play':if(timer!==null){pause();break;}if(step===4){step=-1;void renderReplay();}nextStep();if(step===4)break;q('[data-action="play"] span').textContent=t('暂停回放','Pause replay');timer=globalThis.setInterval(nextStep,1500);break;case'export':void exportRecord();break;}
 });
 bind(q('.ls-task-select'),'change',e=>{opFilter=e.target.value;tasks();});
 bind(q('[role="tablist"]'),'keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;const btns=qa('[data-tab]'),i=btns.findIndex(b=>b===globalThis.document.activeElement);if(i<0)return;e.preventDefault();const k=e.key==='Home'?0:e.key==='End'?btns.length-1:(i+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+btns.length)%btns.length;tabs(btns[k].dataset.tab);btns[k].focus();});
 units();inspect();tasks();evidence();root.dataset.activeTab='space';root.dataset.selected=selectedRoom;root.dataset.replayStep='-1';
 const sceneStatus=status=>{if(disposed)return;q('.ls-stage').dataset.sceneState=status;
  const messages={initializing:t('准备本地三维视图…','Preparing the local 3D view…'),restoring:t('正在恢复图形上下文，等待首帧…','Restoring the graphics context; awaiting the first frame…'),'fallback-loading':t('正在准备软件示意；WebGL 未验收，保持关闭…','Preparing the software schematic; WebGL not accepted and disabled…'),'context-lost':t('图形上下文丢失；可继续使用铺位列表。','Graphics context lost. The unit list remains available.'),unavailable:t('图形视图不可用；铺位、协作与回放文字界面仍可使用。','Graphics unavailable. Unit, network and replay text controls remain available.')};
  const ready=status==='ready'||status==='ready-software';const loading=q('.ls-canvas-loading');loading.hidden=ready;loading.textContent=messages[status]||'';loading.setAttribute('role','status');
  qa('.ls-stage-controls button').forEach(button=>{button.disabled=!ready;});
  if(status==='ready-software'){q('.ls-geometry').textContent=t('软件示意 / 非 WebGL','SOFTWARE / NO WEBGL');q('.ls-stage-sub').textContent=t('软件示意 · WebGL 未验收，保持关闭；非现场资产','Software schematic · WebGL not accepted; disabled. Not a captured asset');}
  else if(status==='ready')q('.ls-geometry').textContent=t('WebGL / 示意模型','WEBGL / SCHEMATIC');
 };
 bind(globalThis.document,'visibilitychange',()=>{if(globalThis.document.hidden)pause();scene?.setActive(!globalThis.document.hidden&&['space','network'].includes(activeTab));});
 sceneStatus('initializing');
 if(loadScene){void import('./spatial-scene.mjs').then(({createSpatialScene})=>{if(disposed)return;try{scene=createSpatialScene(q('.ls-stage'),{locale,onSelect:setSelection,onStatus:sceneStatus});scene.setFloor(floor);scene.setMode(activeTab==='network'?'network':'space');scene.select(activeTab==='network'?selectedNode:selectedRoom);scene.setActive(!globalThis.document.hidden&&['space','network'].includes(activeTab));}catch{q('.ls-stage').replaceChildren();sceneStatus('unavailable');}}).catch(()=>sceneStatus('unavailable'));}else sceneStatus('unavailable');
 return {getState:()=>({activeTab,selectedRoom,selectedNode,floor,step,taskId:task.id,externalActions:0,scene:scene?.info()??null}),dispose(){if(disposed)return;disposed=true;hashGeneration++;pause();for(const off of listeners)off();scene?.dispose();for(const [url,id]of pendingUrls){globalThis.clearTimeout(id);globalThis.URL.revokeObjectURL(url);}pendingUrls.clear();const dialog=q('.ls-plan-dialog');if(dialog.open)dialog.close();root.replaceChildren();root.classList.remove('ls-app');}};
}
